name: Flutter Test

on:
  push:
    branches:
      # - '**'  # runs on push to any branch
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.3'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          releaseNotes: "Automated test build from Github Actions"
          file: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK to TestMu
        run: |
          curl -u "${{ secrets.TESTMU_USERNAME }}:${{ secrets.TESTMU_ACCESS_KEY }}" \
          -X POST "https://manual-api.lambdatest.com/app/upload/realDevice" \
          -F "appFile=@build/app/outputs/flutter-apk/app-release.apk" \
          -F "name=flutter_ci_test_run${{ github.run_number }}" \
          -F "custom_id=flutter-ci-test-app"

      - name: Trigger TestMu test run
        run: |
          curl --location 'https://test-manager-api.lambdatest.com/api/atm/v1/hyperexecute' \
          --header 'Content-Type: application/json' \
          --header "Authorization: Basic ${{ secrets.TESTMU_BASIC_AUTH }}" \
          --data '{
            "test_run_id": "${{ secrets.TESTMU_TEST_RUN_ID }}",
            "concurrency": 1,
            "title": "CI Run #${{ github.run_number }}",
            "region": "eastus"
          }'
